apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/default: "true"
        service: webapp
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: db:3306
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
          image: wordpress:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - echo
                - Define healthcheck command for service
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          name: webapp
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
      serviceAccountName: demos
status: {}
